# -*- coding: utf-8 -*-
"""Base64EncodingExample.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Raqmo0bpD3ypSNLMcaCDMJdHi3v5JqPv
"""

#Encoding Example
import base64

data = "https://github.com/"

# URL and Filename Safe Base64 Encoding
urlSafeEncodedBytes = base64.urlsafe_b64encode(data.encode("utf-8"))
urlSafeEncodedStr = str(urlSafeEncodedBytes, "utf-8")

print(urlSafeEncodedStr)