# -*- coding: utf-8 -*-
"""MissingElementsFromArrayipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1OeAL0NzgB9yT8AWXuVQPMcsMGY01gLQW
"""

def Missingelement(ar,n,i,j):
  t=set(ar)
  for k in range(i, j+1):
    if k not in t:
      print(k, end=' ')


ar=[1,2,4,5]
n=len(ar)
i,j=1,15
Missingelement(ar,n,i,j)

